BUILDING.md
CMakeLists.txt
examples/dial/CMakeLists.txt
examples/echo/CMakeLists.txt
examples/modules/example_module.cpp
src/CMakeLists.txt
src/robot/client.hpp

@stuqdog - No rush on this. It flips the default to building shared libraries and adds some other SDK-ification stuff. The only remaining wrinkle that I'm aware of is that `viam-rust-utils.dylib` has an incorrect install name per https://viam.atlassian.net/browse/RSDK-1996. That only affects macOS builds.

Build with shared libraries by default

---

src/rpc/dial.cpp

Without this fix, the pointer is initialized to a random value and is not nullptr. This causes problems in the rust code that checks if it is null.
To replicate: 
- edit example_dial to not pass a payload. The rust code will return a very non-helpful error.

Fix uninitialized pointer in dial.cpp

---

examples/dial/example_dial.cpp
src/components/camera/camera.cpp
src/components/camera/camera.hpp
src/components/camera/client.cpp
src/components/camera/client.hpp
src/components/component_base.hpp
src/components/generic/client.cpp
src/components/generic/client.hpp
src/components/generic/generic.cpp
src/components/generic/generic.hpp
src/resource/resource_base.hpp
src/robot/client.cpp
src/robot/client.hpp
src/services/service_base.hpp
src/tests/mocks/camera_mocks.cpp
src/tests/mocks/camera_mocks.hpp
src/tests/mocks/generic_mocks.cpp
src/tests/mocks/generic_mocks.hpp

- Move `typed_resource_from_robot` into `RobotClient` as overload of `resource_by_name`
- Stop requiring explicit `template` language in class headers
- move data members of wrappers to `private`, make constructors `protected`

RSDK-2566 - refactor `from_robot`

---

examples/modules/example_module.cpp
src/components/camera/server.cpp
src/components/camera/server.hpp
src/components/generic/server.cpp
src/components/generic/server.hpp
src/module/service.cpp
src/module/service.hpp
src/resource/resource_server_base.hpp
src/rpc/server.cpp
src/rpc/server.hpp

[RSDK-1920](https://viam.atlassian.net/browse/RSDK-1920)
Spawns thread in example module to shutdown server when `SIGTERM` or `SIGINT` is received. Refactors `Server` to be wrapped by various services instead of being global.
This change allows the RDK to remove and reconfigure C++ modules.
[RSDK-1920]: https://viam.atlassian.net/browse/RSDK-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-1920 Fix non-graceful shutdown of modules

---

src/components/camera/camera.hpp
src/components/camera/client.hpp
src/components/camera/server.hpp
src/components/generic/client.hpp
src/components/generic/generic.hpp
src/components/generic/server.hpp
src/registry/registry.hpp
src/robot/client.cpp
src/robot/client.hpp
src/robot/service.hpp
src/rpc/server.cpp
src/rpc/server.hpp

- Provides more comprehensive, doxygen-formatted documentation for `robot`, `camera`, `generic`, `rpc/server`, and `registry`
- Make use of `should_close_channel` in robot client
- make `threads` `private` in robot client
-

RSDK-2703 - Document existing wrappers

---

examples/CMakeLists.txt
examples/motor/CMakeLists.txt
examples/motor/example_motor.cpp
src/CMakeLists.txt
src/components/motor/client.cpp
src/components/motor/client.hpp
src/components/motor/motor.cpp
src/components/motor/motor.hpp
src/components/motor/server.cpp
src/components/motor/server.hpp
src/tests/mocks/mock_motor.cpp
src/tests/mocks/mock_motor.hpp
src/tests/test_motor.cpp

Ticket: https://viam.atlassian.net/browse/RSDK-796
This adds wrappers for the motor component.
Major design decisions:
- Currently hiding all grpc errors (like Camera)
- Doxygen comments are in a slightly different format because of how long they are
- Tests are redundant (I am in favor of de-duping)
- I have moved from `component_mocks.xpp` -> `mock_component.xpp` because we no longer need to have multiple types of mocks for each component

RSDK-796 Server and client wrapper (motor)

---

src/viam/sdk/common/proto_type.cpp
src/viam/sdk/spatialmath/geometry.cpp
src/viam/sdk/spatialmath/orientation.cpp

This fixes the following compile warnings by adding default cases to switch statements:
```
/viam-cpp-sdk/src/viam/sdk/common/proto_type.cpp: In static member function ‘static viam::sdk::ProtoType viam::sdk::ProtoType::of_value(google::protobuf::Value)’:
/viam-cpp-sdk/src/viam/sdk/common/proto_type.cpp:54:1: warning: control reaches end of non-void function [-Wreturn-type]
54 | }
| ^
[45/76] Building CXX object src/viam/sdk/CMakeFiles/viamsdk.dir/spatialmath/geometry.cpp.o
/viam-cpp-sdk/src/viam/sdk/spatialmath/geometry.cpp: In member function ‘viam::common::v1::Geometry viam::sdk::GeometryConfig::to_proto()’:
/viam-cpp-sdk/src/viam/sdk/spatialmath/geometry.cpp:96:1: warning: control reaches end of non-void function [-Wreturn-type]
96 | };
| ^
[47/76] Building CXX object …
```

RSDK-2822 Add default case to switch statements

---

CMakeLists.txt
src/CMakeLists.txt

Removing `src/CMakeLists.txt` means that Github will auto-collapse `src` into `src/viam` like the Python SDK https://github.com/viamrobotics/viam-python-sdk/
I don't think there is any clear benefit of having a `CMakeLists.txt` file at this level and it makes our repo slightly more annoying to navigate.

Remove src/CMakeLists.txt 

---

README.md
src/viam/examples/README.md
src/viam/examples/camera/CMakeLists.txt
src/viam/examples/camera/example_camera.cpp
src/viam/examples/camera/example_config.json
src/viam/examples/dial/example_dial.cpp

This is part of: https://viam.atlassian.net/browse/RSDK-2751
I want to create a model example that the other components can use to show off proper use.
I think it makes sense for us to have a number of examples at the component/service level for two reasons:
1) It allows customers to find the code example they are looking for faster
2) It makes it easier for us to run manual QA on our code and debug customer issues
Though, we might not want/need examples every component (ex: simple ones like encoder).
Important design decisions:
1) `using namespace std` because I think it is cleaner for examples. Happy to remove if we feel otherwise.
2) Included an `example_config.json` that spins up a `fake` camera so people can easily test locally.
3) Placed info for example in root `README.md`. This is …

RSDK-2751 Add Example Camera

---

src/viam/api/CMakeLists.txt
src/viam/sdk/CMakeLists.txt
src/viam/sdk/components/encoder/client.cpp
src/viam/sdk/components/encoder/client.hpp
src/viam/sdk/components/encoder/encoder.cpp
src/viam/sdk/components/encoder/encoder.hpp
src/viam/sdk/components/encoder/server.cpp
src/viam/sdk/components/encoder/server.hpp
src/viam/sdk/tests/CMakeLists.txt
src/viam/sdk/tests/mocks/mock_encoder.cpp
src/viam/sdk/tests/mocks/mock_encoder.hpp
src/viam/sdk/tests/test_encoder.cpp

Ticket: https://viam.atlassian.net/browse/RSDK-2484
Important design decisions:
1) Unsure if Encoder::position_type should be a subclass of Encoder::postion
2) I used peeking-based mocks because it would be difficult to do a behavior-based mock for this component.
Pre-merge:
Bring in refactoring changes. Right now there is so much changing that it would be a waste of time to try and keep up before it is stable.

RSDK-2484 Add encoder wrapper

---

src/viam/api/CMakeLists.txt
src/viam/sdk/CMakeLists.txt
src/viam/sdk/common/linear_algebra.cpp
src/viam/sdk/common/linear_algebra.hpp
src/viam/sdk/components/base/base.cpp
src/viam/sdk/components/base/base.hpp
src/viam/sdk/components/base/client.cpp
src/viam/sdk/components/base/client.hpp
src/viam/sdk/components/base/server.cpp
src/viam/sdk/components/base/server.hpp
src/viam/sdk/tests/CMakeLists.txt
src/viam/sdk/tests/mocks/mock_base.cpp
src/viam/sdk/tests/mocks/mock_base.hpp
src/viam/sdk/tests/test_base.cpp

Ticket: https://viam.atlassian.net/browse/RSDK-797
Important decisions: 
1) For now I replaced common.v1.Vector3 with `typedef std::array<double, 3> Vector3` in `common/linear_algebra.hpp`. I am dubious about this for two reasons:
- If we expose an Vector3, it should be a useful one. I am leaning towards the `boost::numeric::ublas` types
- If we are following the proto file hierarchy, this should be defined in `common/common.hpp` however, that file doesn't exist, and we have instead chosen to create files like `common/utils.hpp` and `common/proto_type.hpp`
2) For testing, I have done a peeking-based testing architecture rather than the current behavior-based mocks. That was done because `base` has no good getter methods to test functionality. 
3) This does not have an example because I …

RSDK-797 Add base wrapper

---

src/viam/sdk/components/base/base.cpp
src/viam/sdk/components/base/base.hpp
src/viam/sdk/components/base/client.cpp
src/viam/sdk/components/base/client.hpp
src/viam/sdk/components/base/server.hpp
src/viam/sdk/components/board/client.hpp
src/viam/sdk/components/camera/camera.cpp
src/viam/sdk/components/camera/camera.hpp
src/viam/sdk/components/camera/client.cpp
src/viam/sdk/components/camera/client.hpp
src/viam/sdk/components/camera/server.cpp
src/viam/sdk/components/camera/server.hpp
src/viam/sdk/components/component.cpp
src/viam/sdk/components/component.hpp
src/viam/sdk/components/encoder/client.hpp
src/viam/sdk/components/encoder/encoder.cpp
src/viam/sdk/components/encoder/encoder.hpp
src/viam/sdk/components/generic/client.cpp
src/viam/sdk/components/generic/client.hpp
src/viam/sdk/components/generic/generic.cpp
src/viam/sdk/components/generic/generic.hpp
src/viam/sdk/components/generic/server.cpp
src/viam/sdk/components/generic/server.hpp
src/viam/sdk/components/motor/client.cpp
src/viam/sdk/components/motor/client.hpp
src/viam/sdk/components/motor/motor.cpp
src/viam/sdk/components/motor/motor.hpp
src/viam/sdk/components/motor/server.cpp
src/viam/sdk/components/motor/server.hpp

Ticket: https://viam.atlassian.net/browse/RSDK-3102
As we have created more components, we have changed how constructors are defined to prevent inlining (part of our styleguide) and to add explicit annotations to constructors when possible.
This brings those changes to the previous components.

RSDK-3102 - Backport constructor changes to previous components

---

src/viam/examples/modules/example_module.cpp
src/viam/sdk/components/base/base.hpp
src/viam/sdk/components/board/board.hpp
src/viam/sdk/components/camera/camera.hpp
src/viam/sdk/components/encoder/encoder.hpp
src/viam/sdk/components/generic/generic.hpp
src/viam/sdk/components/motor/motor.hpp
src/viam/sdk/module/service.cpp
src/viam/sdk/registry/registry.hpp
src/viam/sdk/robot/client.hpp

Remove `<t><t>` tags from `modules` page in documentation
Stop throwing/catching strings anywhere, consistently throw exceptions
Make catches `const&`
Clarify documentation on `validate` method

RSDK-3312 - fix docs, stop throwing strings

---

src/viam/examples/modules/example_module.cpp
src/viam/sdk/CMakeLists.txt
src/viam/sdk/common/utils.cpp
src/viam/sdk/common/utils.hpp

[RSDK-2725](https://viam.atlassian.net/browse/RSDK-2725)
Adds a new utility function `set_logger_severity_from_args` that allows users to set the boost trivial logger's severity to `debug` or `info` if `--log-level=debug` was the third command line argument.
Tested that `BOOST_LOG_TRIVIAL(debug)` statements are printed when server is started with -debug or module is configured with log_level: debug. Tested that `BOOST_LOG_TRIVIAL(debug)` statements are not printed when server is started with -debug but module is configured with `log_level: warn`.
[RSDK-2725]: https://viam.atlassian.net/browse/RSDK-2725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-2725 Add set_logger_severity_from_args

---

etc/docker/tests/run_test.sh

@stuqdog - Hopefully this gives us some insight into the test failures in CI.

Add --output-on-failure to workflow ctest invocation

---

CMakeLists.txt
src/viam/api/CMakeLists.txt

- Reformats the options declarations. That's optional (hah!)
- Defines a new option: `VIAMCPPSDK_USE_LOCAL_PROTOS` which causes proto generation to be performed against proto definitions as currently defined in a sibling directory named `api`.

RSDK-3336 Add support for easily building against a local API repo

---

src/viam/sdk/module/service.cpp
src/viam/sdk/resource/resource_api.cpp
src/viam/sdk/resource/resource_api.hpp

[RSDK-3311](https://viam.atlassian.net/browse/RSDK-3311)
Makes `API` a private member of `Name` instead of having `Name` extend `API`. Removes the `to_api` method in favor of an `api` getter.
`RemoveResource` was not working correctly for modules, as it tried to find the service registered to `name.to_api()`, which incorrectly returned the whole resource name ("rdk:generic:component/printer" instead of "rd:generic:component". I saw the related `TODO` and thought this would be a good fix.
[RSDK-3311]: https://viam.atlassian.net/browse/RSDK-3311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-3311 Make API a member of Name

---

src/viam/examples/mlmodel/example_audio_classification_client.cpp
src/viam/examples/modules/CMakeLists.txt
src/viam/examples/modules/example_mlmodelservice_tflite.cpp

- Fixes three places where I accidentally C++17'd. I didn't catch it because on macOS our brew absl dependency forces us into C++17 mode.
- Adds a missing header for `std::condition_variable` which was needed with libstdc++ but not libc++, so I didn't catch it on macOS builds.
- Fixes a typo in the function-level catch handler for `main` (`excetion` to `exception`).
- Adds a handler for thrown `std::string` since SDK does that.
- Adds an opt-in to build the tflite module (see next)
- Uses FetchContent to build tflite from source to satisfy the tflite dependency for the module. Otherwise, we were trying to get it from system and it just didn't work anywhere. Since this significantly adds to the build time for the SDK, guard it under the flag above.

RSDK-4006 Fixes from working on mlmodel tutorial

---

etc/docker/Dockerfile.debian.bookworm
src/viam/sdk/common/utils.cpp
src/viam/sdk/common/utils.hpp
src/viam/sdk/components/camera/camera.cpp
src/viam/sdk/components/camera/camera.hpp
src/viam/sdk/components/camera/server.cpp
src/viam/sdk/tests/mocks/camera_mocks.cpp
src/viam/sdk/tests/test_camera.cpp

Since we are now returning a general "response metadata" message from proto, this will ensure that future additions to the metadata will not be a breaking change.

Rsdk-4053 patch - create metadata object

---

.clang-tidy
src/viam/examples/modules/example_mlmodelservice_tflite.cpp
src/viam/sdk/services/mlmodel/client.cpp
src/viam/sdk/services/mlmodel/mlmodel.cpp
src/viam/sdk/services/mlmodel/mlmodel.hpp
src/viam/sdk/services/mlmodel/private/proto.cpp
src/viam/sdk/services/mlmodel/private/proto.hpp
src/viam/sdk/services/mlmodel/server.cpp
src/viam/sdk/tests/test_mlmodel.cpp

Updates the C++ SDK to support the changes from https://github.com/viamrobotics/api/pull/279.

RSDK-4196 Add support for flat tensors in mlmodel

---

src/viam/api/config/buf.gen.custom.remote.yaml.in

Stop using remote generation for proto.
Successful proto generation locally, will confirm the github action works as well once this is merged.

RSDK-2069 - stop using remote generation for proto

---

src/viam/examples/dial_api_key/CMakeLists.txt
src/viam/examples/dial_api_key/example_dial_api_key.cpp
src/viam/sdk/rpc/dial.cpp
src/viam/sdk/rpc/dial.hpp

[APP-2519](https://viam.atlassian.net/browse/APP-2519)
```cpp
#include <strings>
#include <vector>
#include <boost/optional.hpp>
#include <viam/api/common/v1/common.pb.h>
#include <viam/api/robot/v1/robot.grpc.pb.h>
#include <viam/sdk/robot/client.hpp>
using namespace viam::sdk;
int main() {
std::string host("airbot-remote-main.74fk6cl2ql.viam.cloud");
DialOptions dial_opts;
Credentials credentials("<key>");
dial_opts.set_type("api-key");
dial_opts.set_entity("<key ID>");
dial_opts.set_credentials(credentials);
boost::optional<DialOptions> opts(dial_opts);
Options options(0, opts);
auto robot = RobotClient::at_address(host, options);
std::cout << "Resources:\n";
for (const ResourceName& resource: *robot->resource_names()) {
std::cout << resource.namespace_() << ":" << resource.type() << …
```

APP-2519: org API key support

---

.github/workflows/linter.yml
CMakeLists.txt
src/viam/examples/modules/simple/main.cpp
src/viam/sdk/CMakeLists.txt

- download the `.a` instead of the `.so` for libviam_rust_utils
- I did this because the `.so` ends up in a nested directory and therefore adds complexity to module bundling; with the `.a`, there's nothing to bundle
- I think this makes the distributable size for a C++ module smaller
- added sstream to examples/modules/simple to fix compile error; not sure why this worked before + is failing now
- convenience change to show lint diff in CI when it fails
- if we want to preserve the old behavior, I can put the file extension behind a config flag
- ~:apple: this works on x86 + arm linux per [this module-example-cpp CI run](https://github.com/viamrobotics/module-example-cpp/actions/runs/6150750042), but I didn't try this on a mac~ -> works on mac now

RSDK-4760 consume .a from rust-utils

---

src/viam/sdk/module/service.cpp

[RSDK-4275](https://viam.atlassian.net/browse/RSDK-4275)
Properly catches exceptions thrown by `construct_resource` in `ModuleService::AddResource` and `ModuleService::ReconfigureResource`. Tested with the example simple module by throwing errors in the constructor and `reconfigure` method.
[RSDK-4275]: https://viam.atlassian.net/browse/RSDK-4275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-4275 Handle `construct_resource` errors in module service

---

etc/docker/tests/run_test.sh
src/viam/examples/modules/complex/CMakeLists.txt
src/viam/examples/modules/complex/README.md
src/viam/examples/modules/complex/client.cpp
src/viam/examples/modules/complex/gizmo/api.cpp
src/viam/examples/modules/complex/gizmo/impl.hpp
src/viam/examples/modules/complex/summation/impl.hpp
src/viam/examples/modules/complex/test_complex_module.cpp

[RSDK-5226](https://viam.atlassian.net/browse/RSDK-5226)
Adds tests for gizmo and summation implementations and API. Fixes bugs in `GizmoClient`. Alters complex module client to have better inputs. Adds simpler constructors for `MyGizmo` and `MySummation`. Updates `run_test.sh` to `ctest` the new complex module test.
Note that these new tests do _not_ test the behavior of the module service (I felt that was out of scope for this ticket, but happy to create a new ticket if that's something we want to test). They also do not test the `MyBase` implementation, as `MyBase` introduces no new API.
[RSDK-5226]: https://viam.atlassian.net/browse/RSDK-5226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-5226 Add tests for gizmo and summation

---

src/viam/examples/dial/example_dial.cpp
src/viam/examples/modules/complex/gizmo/api.cpp
src/viam/examples/modules/complex/summation/api.cpp
src/viam/sdk/common/utils.cpp
src/viam/sdk/common/utils.hpp
src/viam/sdk/components/base/client.cpp
src/viam/sdk/components/board/client.cpp
src/viam/sdk/components/camera/client.cpp
src/viam/sdk/components/encoder/client.cpp
src/viam/sdk/components/generic/client.cpp
src/viam/sdk/components/motor/client.cpp
src/viam/sdk/robot/client.cpp
src/viam/sdk/services/mlmodel/client.cpp
src/viam/sdk/services/motion/client.cpp

Set a placeholder `authority` value for gRPC client contexts.
For reasons that aren't entirely clear to me, the `authority` value in the http headers sent to rust from C++ is set to the socket path to the rust runtime, e.g. `/tmp/proxy-XXXXXX.sock`. This is not a valid uri, and is causing rust to send back a `RST_STREAM` message to C++ rather than sending the request on to the server.
In python (and presumably in linux though I had some difficulty testing this), the header value was set to some valid localhost value (`127.0.0.1:50051`). It's not entirely clear to me where or why this is happening, but fortunately the authority value in the headers is not at all relevant for our use case. By simply setting the authority in the client context to some dummy value that is a syntactically …

RSDK-5194 - set client_ctx auth to a placeholder value

---

src/viam/api/CMakeLists.txt
src/viam/sdk/rpc/dial.cpp
src/viam/sdk/rpc/dial.hpp
src/viam/sdk/services/motion/motion.cpp
src/viam/sdk/services/motion/motion.hpp

Updates pin for `api` buf build commit. Cherry-picks commit from #155 to get @hexbabe's changes for a new `timeout` dial option (makes the C++ SDK compatible with the latest version of `rust-utils`). Adds new `obstacle_detector` type and uses it within motion configurations.

RSDK-5364 RSDK-5195 RSDK-3534

---

src/viam/examples/dial/example_dial.cpp
src/viam/examples/dial_api_key/example_dial_api_key.cpp
src/viam/examples/modules/complex/README.md
src/viam/examples/modules/complex/client.cpp

Prints resources more cleanly in complex client, example dial and API key example dial. Uses const references in for loops for all three (my linter was complaining, and using const refs where possible in for-each loops seems idiomatic). Removes erroneous `namespace` field from `mybase` complex module example JSON (namespace should be `rdk` which is the default). Registers gizmo and summation APIs in complex module client. Adds missing newlines to complex module client ouput. Output now looks like:
```
Resources
name: base1 (type:component subtype:base)
name: motor1 (type:component subtype:motor)
name: gizmo1 (type:component subtype:gizmo)
name: mysum1 (type:service subtype:summation)
name: builtin (type:service subtype:data_manager)
name: builtin (type:service subtype:motion)
name: …
```

Fix complex module client

---

src/viam/examples/modules/complex/CMakeLists.txt

https://viam.atlassian.net/browse/RSDK-5681
Only adds gizmo and summation API source files to `test_complex_module` binary (copy-pasted from the `viamcppsdk_add_boost_test` cmake function). Only adds the generated complex module files as an include directory to the `test_complex_module` binary.
@acmorrow found an issue where I was injecting some complex module stuff into `viamsdk_test` needlessly. This was breaking the encapsulation of the tests.

RSDK-5681 Do not inject complex module stuff into viamsdk_test

---

src/viam/sdk/CMakeLists.txt
src/viam/sdk/common/service_helper.cpp
src/viam/sdk/common/service_helper.hpp
src/viam/sdk/components/encoder/server.cpp
src/viam/sdk/components/encoder/server.hpp
src/viam/sdk/resource/resource_manager.hpp
src/viam/sdk/services/mlmodel/server.cpp

This is my PoC response to the discussion in the Sensor review: https://github.com/viamrobotics/viam-cpp-sdk/pull/174/files#r1386948048
There is a lot to understand in the `ServiceHelper` and `ServiceHelperBase` classes, but I think the boilerplate reduction that it enables (which can be seen most clearly in the `encoder` server changes) is pretty compelling.
I changed the `MLModelServiceServer` class to show how the `ServiceHelper` works in the case where the RPC handler needs to return custom errors and therefore the lambda traffics in `Status` returns, and also did the `EncoderServer` case to show that it also works when there are no `Status` returns and the lambda therefore returns void.
Handling both cases is dealt with through some SFINAE magic.
If this sort of approach is appealing …

RSDK-794 PoC ServiceHelper to simplify service method implementations

---

src/viam/api/CMakeLists.txt
src/viam/sdk/CMakeLists.txt
src/viam/sdk/components/movement_sensor/client.hpp
src/viam/sdk/components/movement_sensor/movement_sensor.cpp
src/viam/sdk/components/movement_sensor/movement_sensor.hpp
src/viam/sdk/components/movement_sensor/server.cpp
src/viam/sdk/components/movement_sensor/server.hpp
src/viam/sdk/components/sensor/client.cpp
src/viam/sdk/components/sensor/client.hpp
src/viam/sdk/components/sensor/sensor.cpp
src/viam/sdk/components/sensor/sensor.hpp
src/viam/sdk/components/sensor/server.cpp
src/viam/sdk/components/sensor/server.hpp
src/viam/sdk/registry/registry.hpp
src/viam/sdk/tests/CMakeLists.txt
src/viam/sdk/tests/mocks/mock_movement_sensor.cpp
src/viam/sdk/tests/mocks/mock_movement_sensor.hpp
src/viam/sdk/tests/mocks/mock_sensor.cpp
src/viam/sdk/tests/mocks/mock_sensor.hpp
src/viam/sdk/tests/test_movement_sensor.cpp
src/viam/sdk/tests/test_sensor.cpp

[RSDK-794](https://viam.atlassian.net/browse/RSDK-794)
Implements wrappers for sensor API.
(cc @cheukt and @acmorrow).
[RSDK-794]: https://viam.atlassian.net/browse/RSDK-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-794 Sensor wrapper

---

src/viam/sdk/CMakeLists.txt
src/viam/sdk/common/client_helper.cpp
src/viam/sdk/common/client_helper.hpp
src/viam/sdk/components/motor/client.cpp
src/viam/sdk/components/motor/client.hpp
src/viam/sdk/components/movement_sensor/client.cpp
src/viam/sdk/components/movement_sensor/client.hpp
src/viam/sdk/components/power_sensor/client.cpp
src/viam/sdk/components/power_sensor/client.hpp
src/viam/sdk/components/sensor/client.cpp
src/viam/sdk/components/sensor/client.hpp

Sorry this took a little longer than expected, I ended up trying several different designs before settling on this one. This is the client side analogue of #178.
@stuqdog and @benjirewis - For main review
CC @zaporter-work and @abe-winter for interest.
Thanks to @abe-winter for starting with `stub_wrapper` which pointed to deriving most of the needed info from the pointer-to-member on the stub type.

RSDK-794 Client side helper to replace `stub_wrapper`

---

codesamples/apis.json

https://viam.atlassian.net/browse/RSDK-5813
https://viam.atlassian.net/browse/RSDK-5788

RSDK-5813 RSDK-5788 Fix code samples and add sensors

---

etc/docker/tests/run_test.sh
src/viam/sdk/components/base/client.cpp

We forgot to add `set -e` to the top of the `run_test.sh` script! This caused the script to not exit early, and because the last command (`popd`) was always succeeding, the test was appearing to pass. This should now be fixed.
Note that the tests here will fail until `Stoppable` is added. Will hold off on merging until that PR is in.

RSDK-5902 - add `set -e` to test bash script

---

src/viam/examples/modules/complex/main.cpp
src/viam/examples/modules/simple/main.cpp
src/viam/examples/modules/tflite/main.cpp
src/viam/sdk/CMakeLists.txt
src/viam/sdk/module/handler_map.cpp
src/viam/sdk/module/handler_map.hpp
src/viam/sdk/module/service.cpp
src/viam/sdk/module/service.hpp
src/viam/sdk/module/signal_manager.cpp
src/viam/sdk/module/signal_manager.hpp

[RSDK-4844](https://viam.atlassian.net/browse/RSDK-4844)
- Renames `ModuleService_` to `ModuleService`
- Adds a `std::shared_ptr<Server> server_` field to `ModuleService`
-  `ModuleService::server_` is created (not started) in the constructor
-  `ModuleService::server_` is shutdown in the `ModuleService` destructor
- Removes `std::shared_ptr<Server>` param from `add_model_from_registry` and `add_api_from_registry` 
- Adds a `SignalManager signal_manager_` field to `ModuleService`
- Changes the `ModuleService::start(std::shared_ptr<Server>)` method to `ModuleService::serve()` and alters its behavior
- `serve` runs the `ModuleService::server_` until the `ModuleService::signal_manager_` finishes waiting
- `serve` logs API/model pairs the module handles
- Creates a new "boilerplate" …

RSDK-4844 Add better boilerplate for module development

---

src/viam/examples/modules/complex/gizmo/api.cpp
src/viam/examples/modules/complex/proto/buf.lock
src/viam/sdk/common/client_helper.hpp
src/viam/sdk/common/utils.cpp
src/viam/sdk/common/utils.hpp
src/viam/sdk/components/board/client.cpp
src/viam/sdk/robot/client.cpp
src/viam/sdk/services/mlmodel/client.cpp
src/viam/sdk/services/motion/client.cpp
src/viam/sdk/services/motion/motion.hpp

Uses a factory function to generate a client ctx with a set authority to minimize both runtime errors and boilerplate.

RSDK-5194 - use factory function for client ctx

---

src/viam/sdk/tests/mocks/mock_motor.hpp

Found while working on #196 for [RSDK-1674](https://viam.atlassian.net/browse/RSDK-1674).
[RSDK-1674]: https://viam.atlassian.net/browse/RSDK-1674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
It seems like the only mock component who needs a change is `mock_motor`.

RSDK-2747: use attributemap in mocks

---

BUILDING.md

[RSDK-5682](https://viam.atlassian.net/browse/RSDK-5682)
References the "Setting `PKG_CONFIG_PATH`" section right after the initial `cmake` instructions in case a MacOS user immediately encounters a missing OpenSSL target.
cc @npentrel
[RSDK-5682]: https://viam.atlassian.net/browse/RSDK-5682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-5682 Further clarify PKG_CONFIG_PATH in BUILDING.md

---

.clang-tidy
src/viam/sdk/registry/registry.cpp
src/viam/sdk/resource/resource_api.cpp
src/viam/sdk/resource/resource_manager.cpp
src/viam/sdk/resource/resource_manager.hpp
src/viam/sdk/rpc/dial.cpp
src/viam/sdk/rpc/server.cpp
src/viam/sdk/services/mlmodel/client.cpp
src/viam/sdk/services/mlmodel/server.cpp
src/viam/sdk/services/motion/client.cpp
src/viam/sdk/services/motion/server.cpp
src/viam/sdk/spatialmath/geometry.cpp

- No longer disable `performance-move-const-arg` in `clang-tidy`. 
- Necessary fixes for `clang-tidy` to pass.

RSDK-3019 - add clang-tidy performance-move-const-arg

---

codesamples/apis.json
src/viam/examples/dial/example_dial.cpp
src/viam/examples/dial_api_key/example_dial_api_key.cpp
src/viam/sdk/robot/client.cpp

`apis.json` was still passing `FooClient` as the client type for code samples, leading to `resource_by_name<FooClient>(...)` rather than the now-correct `resource_by_name<Foo>(...)`. This PR fixes that.

RSDK-6726 - update client types in c++ code samples

---

.github/workflows/docs.yml
.github/workflows/linter.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update_protos.yml

Remove use of self-hosted runners from the SDK.

RSDK-7410 - remove self-hosted runners

---

.gitignore
src/viam/api/CMakeLists.txt
src/viam/examples/modules/complex/proto/buf.lock
src/viam/sdk/components/board.cpp
src/viam/sdk/components/board.hpp
src/viam/sdk/components/private/board_client.cpp
src/viam/sdk/components/private/board_client.hpp
src/viam/sdk/components/private/board_server.cpp
src/viam/sdk/components/private/board_server.hpp
src/viam/sdk/tests/mocks/mock_board.cpp
src/viam/sdk/tests/mocks/mock_board.hpp
src/viam/sdk/tests/test_board.cpp

This turned out to be two problems combined! 1) update the SDK to use a more recent version of the protobufs in the API repo, and then 2) remove the `Status` RPC from the boards. The PR isn't quite done: I'm unsure how this should interact with https://github.com/viamrobotics/viam-cpp-sdk/pull/230, which is where the compiled version of the updated protos is. but the rest I think is ready for a look.
Updating the protobufs was harder than I expected: https://github.com/viamrobotics/api/pull/470 (unrelated to boards) added a new type that had not been used previously, which meant that getting it to work required updating CMakeLists.txt to include the Google libraries for the new type.
Changes to boards:
- `get_status` doesn't exist any more. You can get the standard status from a component …

[RSDK-7310] Update the board interface

---

.gitignore
src/viam/api/CMakeLists.txt
src/viam/examples/modules/complex/proto/buf.lock
src/viam/sdk/components/board.cpp
src/viam/sdk/components/board.hpp
src/viam/sdk/components/private/board_client.cpp
src/viam/sdk/components/private/board_client.hpp
src/viam/sdk/components/private/board_server.cpp
src/viam/sdk/components/private/board_server.hpp
src/viam/sdk/tests/mocks/mock_board.cpp
src/viam/sdk/tests/mocks/mock_board.hpp
src/viam/sdk/tests/test_board.cpp

...which was overwritten by an automated process after merging into the branch on PR 230.
Looks like this is going to have merge conflicts, which I'll try resolving in just a moment...

[RSDK-7310] Redo PR #231

---

src/viam/api/buf.lock
src/viam/examples/modules/complex/proto/buf.lock
src/viam/sdk/services/motion.hpp
src/viam/sdk/services/private/motion_client.cpp
src/viam/sdk/services/private/motion_client.hpp
src/viam/sdk/services/private/motion_server.cpp
src/viam/sdk/spatialmath/geometry.cpp
src/viam/sdk/spatialmath/geometry.hpp
src/viam/sdk/tests/mocks/mock_motion.cpp
src/viam/sdk/tests/mocks/mock_motion.hpp
src/viam/sdk/tests/test_motion.cpp

We are updating the python SDK to match the following changes made in API (https://github.com/viamrobotics/api/commit/503a9a41e4ef9c8e5c8399a8890c6b2ae923d96b)
We would like to also explicitly call out the changes reviewers should be aware of:
1. GeoObstacle has been renamed into GeoGeometry - we note that they store the same information and this is just a re-name.
This means that the return type of GetObstacles in the navigation service has changes from GeoObstacle into GeoGeometry, but the navigation service is not yet a thing in this SDK so nothing to worry about here :)
2. We have added an argument to the motion service method MoveOnGlobe. The argument is called bounding_regions and is a list of GeoGeometrys
3. The motion service method MoveOnGlobe also takes in a list of obstacles of …

RSDK-7463 - Update Motion service in C++ SDK

---

src/viam/sdk/components/board.cpp
src/viam/sdk/components/board.hpp
src/viam/sdk/components/private/board_client.cpp
src/viam/sdk/components/private/board_client.hpp
src/viam/sdk/components/private/board_server.cpp
src/viam/sdk/tests/mocks/mock_board.cpp
src/viam/sdk/tests/mocks/mock_board.hpp
src/viam/sdk/tests/test_board.cpp

Surprisingly, we don't need a protobuf update (from https://github.com/viamrobotics/api/pull/492) because we're already using the new protobufs and have just been ignoring the extra data they hold!
Everything compiles and the tests all pass, though I haven't tried it out more than that.

[RSDK-7151] Update analog reader responses to include accuracy data

---

src/viam/sdk/components/camera.cpp
src/viam/sdk/components/camera.hpp
src/viam/sdk/tests/mocks/camera_mocks.cpp

[RSDK-7775](https://viam.atlassian.net/browse/RSDK-7775)
[RSDK-7775]: https://viam.atlassian.net/browse/RSDK-7775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
From Jira^: Right now, we’re not returning the mime type. Update the C++ SDK wrapper to match the Properties API method
In this PR, I add `mime_types` to the camera component files, extracting the data from the proto when `Camera::properties Camera::from_proto` is called, adding it to the new `mime_types` field in camera properties. I added an appropriate test to make sure this happens correctly.

[RSDK-7775]   Update Camera.Properties Response in C++ SDK to match API

---

.github/workflows/docs.yml

Locks doxygen version at `1.10.0` to avoid `glibc` version conflicts.

RSDK-7858 - lock in doxygen version

---

src/viam/api/CMakeLists.txt
src/viam/sdk/CMakeLists.txt
src/viam/sdk/components/arm.cpp
src/viam/sdk/components/arm.hpp
src/viam/sdk/components/private/arm_client.cpp
src/viam/sdk/components/private/arm_client.hpp
src/viam/sdk/components/private/arm_server.cpp
src/viam/sdk/components/private/arm_server.hpp
src/viam/sdk/registry/registry.cpp
src/viam/sdk/rpc/server.cpp
src/viam/sdk/tests/CMakeLists.txt
src/viam/sdk/tests/mocks/mock_arm.cpp
src/viam/sdk/tests/mocks/mock_arm.hpp
src/viam/sdk/tests/test_arm.cpp

See [RSDK-7939](https://viam.atlassian.net/browse/RSDK-7939)
Maybe the only odd thing about this is the `KinematicsData` variant, a design I arrived at after discussion with @acmorrow 
It's an adaptation of https://github.com/viamrobotics/api/blob/main/proto/viam/common/v1/common.proto#L194
The variant is meant to introduce different types for different file types. In the case of unspecified data we do not store the bytes, but maybe there is a compelling reason to do so. 
Note also that this is technically part of common but I put it in the arm module code because it's not being used elsewhere, but I can move it if that's an issue
[RSDK-7939]: https://viam.atlassian.net/browse/RSDK-7939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-7939: Add arm component

---

src/viam/sdk/CMakeLists.txt
src/viam/sdk/robot/client.cpp
src/viam/sdk/rpc/dial.cpp
src/viam/sdk/rpc/dial.hpp
src/viam/sdk/rpc/message_sizes.hpp
src/viam/sdk/rpc/private/viam_grpc_channel.cpp
src/viam/sdk/rpc/private/viam_grpc_channel.hpp
src/viam/sdk/rpc/server.cpp
src/viam/sdk/tests/mocks/camera_mocks.cpp
src/viam/sdk/tests/test_robot.cpp
src/viam/sdk/tests/test_utils.cpp
src/viam/sdk/tests/test_utils.hpp

Fixes an issue where the gRPC 4mb message size limit was being hit despite https://github.com/viamrobotics/viam-cpp-sdk/pull/254
Per this issue discussion we now change the channel args as well: https://github.com/tensorflow/serving/issues/1382#issuecomment-730428996
This needs to be set every time we create a channel, so I introduced a helper which sets the parameters and passes the args. I believe this is the best we can do since grpc Channel is `final` and only constructible by a `Create` function and you can't set args on an already-created channel 
cc @stuqdog @acmorrow

RSDK-8081 Fix max message size limit

---

.gitignore
src/viam/sdk/common/client_helper.hpp
src/viam/sdk/components/private/board_client.cpp

Modifies `ClientHelper` to be able to handle streaming requests such as `Board::stream_ticks` or forthcoming `InputController::stream_events`. This work was factored out of the input controller branch, and the new method is able to handle both of them. 
`ClientHelper` is now templated on the stub PMF type, which is one of two introduced alias declarations, either `SyncMethodType` or `StreamingMethodType`. This replaces the `using PFn` declaration. Rather than do this, I would love to be able to write something like
```cpp
using PFn = std::conditional_t<
is_sync_response_v<ResponseType>
SyncMethodType<...>,
StreamingMethodType<...>
>
```
but at a glance it does not appear possible to do through anything gRPC gives us on response types. 
Note it would be possible to forgo the …

Streamable client helper

---

src/viam/sdk/common/proto_value.hpp

This should fix failures seen it the latest draft release, see eg 
https://github.com/viamrobotics/viam-cpp-sdk/actions/runs/10457244069/job/28956432798#step:7:326
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54483#c13
For whatever reason this was only failing on the aarch c++14 linux builds, although it seems they were correct to fail it.

Fix aarch build

---

src/viam/sdk/components/camera.cpp
src/viam/sdk/components/camera.hpp
src/viam/sdk/components/private/camera_server.cpp
src/viam/sdk/tests/mocks/camera_mocks.cpp

- Added support for mapping `frame_rate` from the GetPropertiesResponse proto to the Camera::properties struct in `Camera::from_proto `
- Added `frame_rate` to properties struct 
- Added `frame_rate` to `getPropertiesResponse` func in camera_server.cpp 
- Added `frame_rate` to fake_properties in camera_mocks.cpp to test

RSDK-8829: Add frame_rate to cpp sdk

---

.github/workflows/docker.yml

- add CI yaml for uploading the docker base images to ghcr
Allow people to use these without having to build them on-laptop
Github CI requires a workflow to be on the main branch before it can be tested; this hasn't been tested and may require another PR. (Once the workflow has ever been on the main branch, it can then be run from other branches).

build docker base images in CI

---

src/viam/sdk/components/arm.cpp
src/viam/sdk/components/arm.hpp
src/viam/sdk/components/private/arm_client.cpp
src/viam/sdk/components/private/arm_client.hpp
src/viam/sdk/components/private/arm_server.cpp
src/viam/sdk/components/private/arm_server.hpp
src/viam/sdk/tests/mocks/mock_arm.cpp
src/viam/sdk/tests/mocks/mock_arm.hpp
src/viam/sdk/tests/test_arm.cpp

I took a first pass at adding this new function to the sdk but don't completely understand everything that is required in doing this, so I'm hoping this can be a launching point to learn more about coding practices in this environment

Add MoveThroughJointPositions to Arm component

---

src/viam/sdk/services/private/motion_server.cpp

Removes some instances where a default-constructed and hence null optional was being deref'd

remove null opt derefs

---

src/viam/sdk/services/navigation.hpp

Following up on #323 and providing slightly more context for docstrings.  Since a MoveOnGlobe stub already exists on the motion service we should be able to close the ticket now.

RSDK-3589 audit nav service docstrings

---

src/viam/sdk/common/utils.cpp
src/viam/sdk/common/utils.hpp
src/viam/sdk/robot/client.hpp
src/viam/sdk/services/motion.hpp
src/viam/sdk/tests/mocks/camera_mocks.cpp
src/viam/sdk/tests/mocks/mock_motion.cpp

Fixes the incorrect `std::chrono::time_point` type used throughout the SDK. I have opted to call this `viam::sdk::time_pt` so as not to create name clashes with `time_point` for anyone doing `using namespace std::chrono`.

RSDK-6574: Fix use of `time_point`

---

src/viam/sdk/common/client_helper.hpp
src/viam/sdk/common/service_helper.hpp
src/viam/sdk/common/utils.cpp
src/viam/sdk/common/utils.hpp
src/viam/sdk/components/private/board_client.cpp
src/viam/sdk/components/private/board_server.cpp
src/viam/sdk/components/private/camera_client.cpp
src/viam/sdk/components/private/camera_server.cpp
src/viam/sdk/config/resource.cpp
src/viam/sdk/config/resource.hpp
src/viam/sdk/module/handler_map.cpp
src/viam/sdk/module/service.cpp
src/viam/sdk/resource/resource_api.cpp
src/viam/sdk/resource/resource_api.hpp
src/viam/sdk/resource/resource_manager.hpp
src/viam/sdk/robot/client.cpp
src/viam/sdk/robot/service.cpp
src/viam/sdk/services/private/motion_client.cpp
src/viam/sdk/services/private/motion_server.cpp
src/viam/sdk/tests/test_common.cpp
src/viam/sdk/tests/test_resource.cpp

Some other stuff arguably would have fit under this ticket but wanted to keep this PR more digestible

RSDK-9449 Miscellaneous further proto cleanups

---

src/viam/examples/dial/example_dial.cpp
src/viam/examples/dial_api_key/example_dial_api_key.cpp
src/viam/examples/modules/complex/client.cpp
src/viam/examples/modules/complex/main.cpp
src/viam/examples/modules/complex/test_complex_module.cpp
src/viam/examples/modules/simple/main.cpp

remove api imports from examples

---

src/viam/examples/modules/simple/README.md

This should be replaced with a new example (see RSDK-9719) but for now we don't want a link pointing people to stuff that hasn't been updated in two years

Remove reference to old module-example-cpp

---

src/viam/examples/modules/simple/client.cpp
src/viam/examples/modules/simple/main.cpp

Replaces the prior "simple" module example with one that just implements a Sensor component, in line with eg Python SDK https://github.com/viamrobotics/viam-python-sdk/tree/main/examples/simple_module

RSDK-9719: Simple module sensor

---

bin/run-clang-format.sh
src/viam/api/CMakeLists.txt
src/viam/examples/modules/complex/proto/buf.lock
src/viam/sdk/CMakeLists.txt
src/viam/sdk/config/resource.cpp
src/viam/sdk/config/resource.hpp
src/viam/sdk/registry/registry.cpp
src/viam/sdk/services/discovery.cpp
src/viam/sdk/services/discovery.hpp
src/viam/sdk/services/private/discovery_client.cpp
src/viam/sdk/services/private/discovery_client.hpp
src/viam/sdk/services/private/discovery_server.cpp
src/viam/sdk/services/private/discovery_server.hpp
src/viam/sdk/tests/CMakeLists.txt
src/viam/sdk/tests/mocks/mock_discovery.cpp
src/viam/sdk/tests/mocks/mock_discovery.hpp
src/viam/sdk/tests/test_discovery.cpp
src/viam/sdk/tests/test_utils.cpp
src/viam/sdk/tests/test_utils.hpp

This PR adds the Discovery Service wrapper to the C++ SDK.
I mainly followed the pattern in #323.
I followed the `arm.get_geometries` method pattern to return an array of a `ResourceConfig` from `discovery.discover_resources`, which is intended to return a valid config with meaningful attributes for physically connected devices to viam-server.

[RSDK-9624] Add discovery service

---

src/viam/sdk/common/proto_value.cpp
src/viam/sdk/common/proto_value.hpp

MSVC revealed that the way I was previously overloading member functions was not legal. In particular you can't do
```cpp
struct X {
void f(); // no ref qualifier
void f() const& // ref qualifier
};
```

conformant ref qualified overloads

---

.github/workflows/release.yml

trying to fix https://github.com/viamrobotics/sdk-integration-tests/actions/runs/14177887867
we were previously grabbing latest cmake which recently bumped to 4.0

try pinning cmake version

---

CMakeLists.txt
conanfile.py
src/viam/sdk/CMakeLists.txt
src/viam/sdk/common/private/service_helper.hpp
src/viam/sdk/module/service.cpp
src/viam/sdk/rpc/dial.cpp
src/viam/sdk/rpc/private/viam_rust_utils.h
src/viam/sdk/rpc/private/viam_rust_utils_stubs.cpp

- Ensure `__cplusplus` is set right on Windows builds.
- Don't download or link to `viam_rust_utils` on Windows.
- Redirect the `viam_rust_utils` entry points to `abort` on Windows.
- Adjust `viamapi` library name on Windows and apply `/WHOLEARCHIVE`
- Use `std::invoke_result_t` instead of `result_of` in C++17, where the latter is deprecated
- Add windows headers where needed.

[RSDK-10385] Windows build system improvements and rust_utils workarounds

---

.gitignore
conanfile.py

- The presets shouldn't get checked in, so, gitignore them
- We use xtensor publicly, so the dependency should have transitive headers.

[RSDK-10385] Misc conan improvements

---

CMakeLists.txt

Small tweak so we get better SDK version selection behavior on Windows. I'm not 100% sure we need this, but it seems pretty safe given that we have no existing Windows usage or platform dependencies we would conflict with.

[RSDK-10385] Use a newer CMake minimum for Windows

---

src/viam/sdk/module/service.cpp
src/viam/sdk/robot/client.cpp
src/viam/sdk/robot/client.hpp
src/viam/sdk/rpc/dial.cpp
src/viam/sdk/rpc/dial.hpp
src/viam/sdk/tests/test_robot.cpp

There was a sigabrt in recent module integration tests that revealed some UB where we sometimes accidentally double-free the memory managed by a `std::string`. Zero clue as to why logging brought this up but it is indeed something we'd want to fix anyway.
Contains some drive-by changes as well

Fix sigabrt in module integration tests

---

src/viam/examples/modules/complex/proto/buf.lock
src/viam/sdk/module/service.cpp
src/viam/sdk/rpc/server.cpp
src/viam/sdk/rpc/server.hpp

modeled after https://github.com/viamrobotics/viam-python-sdk/pull/904, tested similarly with a modified timeout in simple module.

RSDK-8424 - respect ctx deadline when adding module resources

---

src/viam/sdk/module/service.cpp

cherry picked from the dial-direct PR, figured we want this in main sooner than later

reset parent to prevent double close

---

conanfile.py

turns out you are not allowed to string compare against `14` and `gnu14` because `gnu14` is not supported on windows

fix detection of c++14

---

README.md

Added a section to the README to make the location of the tests and how to run the tests more clear.

[RSDK-7426] Make it more obvious how to run the tests for the C++ SDK

---

src/viam/sdk/module/service.cpp
src/viam/sdk/resource/reconfigurable.cpp
src/viam/sdk/resource/reconfigurable.hpp
src/viam/sdk/resource/resource_manager.cpp
src/viam/sdk/resource/stoppable.cpp
src/viam/sdk/resource/stoppable.hpp
src/viam/sdk/tests/mocks/mock_robot.cpp

Fixes logic in ReconfigureResource which would have prevented any action on non-Reconfigurable resources

RSDK-11050: Reconfigure fix

---

src/viam/sdk/module/service.cpp
src/viam/sdk/resource/resource_manager.cpp
src/viam/sdk/resource/resource_manager.hpp
src/viam/sdk/spatialmath/orientation.cpp

third time's the charm? this should finally fix the  _`always-rebuild`_ logic in `ReconfigureResource`, making sure that the old resource is destructed before the new one is created. this was causing issues with realsense and would cause issues for any other unique or global resource which has sole ownership of a device, socket, etc.
this adds an overload of `replace_one` which takes a construction callback, bringing the logic closer to that of eg python
https://github.com/viamrobotics/viam-python-sdk/blob/main/src/viam/module/module.py#L253
i marked the old one as deprecated for now but we may just want to remove it entirely 
cc @hexbabe @acmorrow

RSDK-11289: Fix logic in replace_one

---

etc/docker/base-images/Dockerfile.debian.bullseye

The backports apt repository URL looks to no longer be valid:
```
=> CACHED [ 6/10] RUN apt-add-repository -y 'deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-15 main'              0.0s
=> CACHED [ 7/10] RUN apt-add-repository -y 'deb http://deb.debian.org/debian bullseye-backports main'                       0.0s
=> ERROR [ 8/10] RUN apt-get update                                                                                          4.7s
------                                                                                                                             
> [ 8/10] RUN apt-get update:                                                                                                     
1.366 Hit:1 http://deb.debian.org/debian bullseye InRelease …
```

Update debian bullseye backports url

---

.github/workflows/ai-updater.yml

It turns out the update protos workflow creates a branch called workflow/update-protos (whereas in the Python SDK it is called workflow/update-proto). This PR fixes this inconsistency in the AI Updater.

fix branch name in ai-updater workflow

---

BUILDING.md
src/viam/sdk/components/camera.hpp
src/viam/sdk/components/private/camera_client.cpp
src/viam/sdk/components/private/camera_client.hpp
src/viam/sdk/components/private/camera_server.cpp
src/viam/sdk/tests/mocks/camera_mocks.cpp
src/viam/sdk/tests/mocks/camera_mocks.hpp
src/viam/sdk/tests/test_camera.cpp

This PR is part of the SDK changes of[ the Consolidate GetImage(s) project](https://docs.google.com/document/d/1Q4UWacS76tx3ohOjS98aei2UdHU4XdyWsFldQHTQ_7s/edit?usp=sharing)
It
- Updates the GetImages signature to be in line with [the new camera.proto](https://github.com/viamrobotics/api/blob/main/proto/viam/component/camera/v1/camera.proto)
- Updates unit tests accordingly
Built a local RealSense module executable with its C++ SDK pinned to this commit https://github.com/viamrobotics/viam-cpp-sdk/pull/481/commits/d8292dfdc29fcc51ee84f09c9bdb211c778d7857
Added logging to make sure that the server is receiving extra and filter_source_names. It was
```
8/27/2025, 2:16:11 PM info Viam C++ SDK     [src/camera_realsense.cpp:439] extra keys: ["foo"]   log_ts 2025-08-27T14:16:11.789Z
8/27/2025, …
```

[RSDK-11703, RSDK-11602] Update C++ GetImages signature
